### ISSUE TITLE
Defaults defined in nested objects within the schema are not initialized unless the nested object is defined in the instance 

### ISSUE THREAD

**Issue by amirahav** [kubernetes-sigs/kro#167]
### Description

**Observed Behavior**:
When defining a nested object within the schema, the nested object is not initialize, and instance creation fails erroring out on undefined schema properties.
     
as an example, assume this partial ResourceGroup:
```
apiVersion: kro.run/v1alpha1
kind: ResourceGroup
metadata:
  name: api-deployment
spec:
  schema:
    apiVersion: v1alpha1
    kind: ApiDeployment
    spec:
      labels: map[string]string | default={}
      service:
        targetPort: string | default="http" required=false
      iamRole:
        inlinePolicies: map[string]string | default={}
        name: string | required=true
```

And this instance
```
apiVersion: kro.run/v1alpha1
kind: ApiDeployment
metadata:
  name: test-api
  namespace: kro
spec:
  iamRole:
    name: my-iam-role
```

Will fail to be created because `spec.service.targetPort` will not be defined.

**Expected Behavior**:
Nested objects defined within the schema are initialized correctly and default values are set.

**Reproduction Steps** (Please include `ResourceGroup` and `Instances` files):

**Versions**:
- kro version: 0.1.0
- Kubernetes Version (`kubectl version`): v1.31.2-eks-7f9249a

**Involved Controllers**:
- Controller URLs and Versions (if applicable):

**Error Logs** (if applicable)**:
```
Paste any relevant logs here
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by newtondev** [comment]
Hi @amirahav, thanks for raising this. What is really interesting is that if provide the configuration as:

```yaml
apiVersion: kro.run/v1alpha1
kind: ApiDeployment
metadata:
  name: test-api
  namespace: kro
spec:
  service: {}
  iamRole:
    name: my-iam-role
```

Then it works.
