### ISSUE TITLE
Mega Feature: Implement collections (for loops) in RGDs

### ISSUE THREAD

**Issue by a-hilaly** [kubernetes-sigs/kro#17]
Add support for collections in ResourceGroups to allow dynamic creation of multiple similar resources.. This will probably need a design and a review. It also needs the garbage collection mechanisms to be in place.

- Implement iteration based on a range or list
- Add current iteration index reference within resource definitions
- Support specifying "deployment strategies" for collection types

Example:
```yaml
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: worker-pool
spec:
  schema:
    apiVersion: v1alpha1
    kind: WorkerPool
    spec:
      workers: "[]string"
      image: string

  resources:
    - id: workerPods
      forEach:
        - worker: ${schema.spec.workers}
      template:
        apiVersion: v1
        kind: Pod
        metadata:
          name: ${schema.metadata.name + '-' + worker}
        spec:
          containers:
            - name: app
              image: ${schema.spec.image}
```

**Comment by gfrey** [comment]
Index reminds me of Terraform's count iteration concept. This had plenty of downsides when combined with lists of actual configuration values. Any change to the that list would result in modification on all subsequent list items. This was eventually solved with `for_each` based on sets or dicts. Then the item or key was used as part of the resource address. This made things a lot more stable. Possible solution could be to change the relevant part of the example above to:
```
collection:
  items: ${range(0, spec.replicas)}
  deploymentStrategy: RollingUpdates
  definition:
    metadata:
      name: pod-unit-${item}
```
An immediate application for this would be distribution of a VPC's subnets to availability-zones. Then the list of `items` would be the AZs (or maybe a dictionary from AZ to CIDR block).

A follow-up question would be how the resources of a collection can be queried? In the subnets application I would need to associate a NetworkACL with all these subnets. How could that be done?

**Comment by greghaynes** [comment]
Would the above solutions be limited in that they cannot allow for multiple sources of iteration within a single resource? 

Here's a contrived example: Imagine we want to support a RG which supports defining multiple containers where some values are defaulted below each container.
```yaml
apiVersion: kro.run/v1alpha1
kind: ResourceGroup
metadata:
  name: Application
spec:
  apiVersion: v1alpha1
  kind: Application
  definition:
    spec:
      name: string
    containers:
      - name: frontend
        image: nginx
      - name: backend
        image: nginx
```

This would mean it needs to be capable of rendering out a *single* Deployment resource, but within that deployment resource it iterates over the collection of containers within our RG:

```yaml
  resources:
    - id: deployment
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: ${schema.spec.name}
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: deployment
          template:
            metadata:
              labels:
                app: deployment
            spec:
              containers:
               ${ NEEDS CONTAINER COLLECTION HERE }
```

One thought on how to approach this is to introduce a vars layer like the following:

```yaml
apiVersion: kro.run/v1alpha1
kind: ResourceGroup
metadata:
  name: Application
spec:
  apiVersion: v1alpha1
  kind: Application
  definition:
    spec:
      name: string
    containers:
      - name: frontend
        image: nginx
      - name: backend
        image: nginx
  vars:
    - name: deploymentContainers
      function: map
      input: schema.spec.containers
      render:
        - name: ${item.name}
          image: ${item.image}
          resources:
                requests:
                  memory: "64Mi"
                  cpu: "250m"
  resources:
    - id: deployment
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: ${schema.spec.name}
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: deployment
          template:
            metadata:
              labels:
                app: deployment
            spec:
              containers:
                ${vars.deploymentContainers}
```

**Comment by btwseeu78** [comment]
How about object bases substitution, like how helm template works, like toYaml function in helm.

we are substituting {{ $schema.spec.containers } let containers be an object rather than  value type.
so we can do like this.

```yaml
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: my-application
spec:
  # kro uses this simple schema to create your CRD schema and apply it
  # The schema defines what users can provide when they instantiate the RGD (create an instance).
  schema:
    apiVersion: v1alpha1
    kind: Application
    spec:
      containers:
        - name: conatiner1
        - name: container2
```

```yaml
containers:
{{ $.schema.spec.containers }}

```

**Comment by VladRico** [comment]
Hi there !
I'm really interested about this feature. Has a solution been adopted ? Or is it still open to proposals ?

**Comment by handicraftsman** [comment]
This tbh.

As somebody who's using a similar tool, but built in-house, I absolutely understand the need of having ability to e.g. define several databases, containers, or whatever in a SINGLE resource manifest.

**Comment by gjrtimmer** [comment]
I am very intrested. Also I would like to give another use-case example. I am using CNPG (CloudNative Postgres). `Kro` allows me to deploy a new cluster bootstrapped from S3.

Currently the `CustomTypes` solves my issue to populate the `roles` spec of the cnpg spec. I want, however, to be able to create a `kro` attribute like `databases`. And the loop of this list and create the a resource per database name.

```yaml
---
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: cnpg.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: PostgreSQLCluster
    types:
      role:
        name: string | required=true description="Role name"
        ensure: string | required=false default="present" description="Ensure the role is present or absent"
        login: boolean | required=false default=true description="Role can login"
        passwordSecret:
          name: string | required=true description="Secret name for the role password"
    spec:
      name: string | required=true description="Name of the PostgreSQL cluster"
      namespace: string | required=true default="postgres" description="Namespace for the PostgreSQL cluster"
      replicas: integer | required=true default=3 description="Number of PostgreSQL replicas"
      bootstrap:
        initdb: boolean | required=false default=false description="Initialize new cluster"
        recovery:
          enabled: boolean | required=false default=false description="Initialize cluster from recovery"
          source: string | required=false description="Recovery source for the cluster"
          version: integer | default=0 required=false
      roles: '[]role | required=false description="List of roles to be created in the cluster"'
      backup:
        version: integer | required=false default=1 description="Backup version"
        retention: string | required=false default="30d" description="Backup retention policy"
    validation:
      # Require either initdb or recovery.enabled to be true
      - expression: >
          (has(self.bootstrap) && has(self.bootstrap.initdb) && self.bootstrap.initdb)
          ||
          (has(self.bootstrap) && has(self.bootstrap.recovery) && has(self.bootstrap.recovery.enabled) && self.bootstrap.recovery.enabled)
        message: "Set spec.bootstrap.initdb=true or spec.bootstrap.recovery.enabled=true."

      # If recovery.enabled is true, source must be non-empty
      - expression: >
          !(has(self.bootstrap) && has(self.bootstrap.recovery) && has(self.bootstrap.recovery.enabled) && self.bootstrap.recovery.enabled)
          ||
          (has(self.bootstrap.recovery.source) && size(self.bootstrap.recovery.source) > 0)
        message: "When recovery is enabled, spec.bootstrap.recovery.source must be non-empty."

      # If recovery.enabled is true, version must be non-zero
      - expression: >
          !(has(self.bootstrap) && has(self.bootstrap.recovery) && has(self.bootstrap.recovery.enabled) && self.bootstrap.recovery.enabled)
          ||
          (has(self.bootstrap.recovery.version) && self.bootstrap.recovery.version != 0)
        message: "When recovery is enabled, spec.bootstrap.recovery.version must be non-zero."
  resources: []

```

Now I need to be able to turn the list of `databases` into the following resource, one per database name in the array.

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: ${database.name}
  namespace: postgres
  labels:
    cnpg.io/cluster: shared
    cnpg.io/database: ${database.name}
spec:
  name: ${database.name}
  owner: ${database.role}
  cluster:
    name: ${name}
  extensions: []
  databaseReclaimPolicy: retain
```

**Comment by AtzeDeVries** [comment]
This also has my interest. Fixing loops is kinda a must have feature. I do like the crossplane solution, which kinda boils down to, you can put data object and state into a function, which can be written in what ever and then you can a expected data object out, which can be consumed by kro.

**Comment by abhijith-darshan** [comment]
Currently we ended up doing a helm template of the resource graph instance and applied it via ArgoCD 🙂

But this would be a lot easier with kro native functionality. The whole point for us was to move away from helm and we ended up using helm to template and apply multiple instances of the resource graph 😅

**Comment by fabio-sv** [comment]
Good day!

Seeking clarity on whether looping is possible within a resource?
The docs seem to indicate that this might be possible under the [complete example](https://kro.run/docs/concepts/rgd/schema#complete-example), though it doesn't indicate how the `schema.spec.env` input is used within the resource.

I have a use case where I need to create an API of the form:

```yaml
apiVersion: company.com/v1alpha1
kind: Application
metadata:
  name: my-app-instance
spec:
  # ...
  env:
    FEATURE_FLAG_A: "true"             # user-defined environment variables
    FEATURE_FLAG_B: "false"
    API_URL: "https://api.example.com"
```

How would the implementation of `schema.spec.env` look in the RGD?

```yaml
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: application
spec:
  schema:
    apiVersion: v1alpha1
    kind: Application
    group: company.com
    spec:
      # ...
      env: "map[string]string"

  resources:
    - id: config
      # ...
    - id: service
      # ...

    - id: deployment
      template:
        # ...
        spec:
          containers:
            - name: ${schema.spec.name}
              env:
                # default environment variables defined
                - name: ENVIRONMENT
                  value: ${config.data.account-id}
                - name: REGION
                  value: ${config.data.region}
                # TODO: additional environment variables from schema.spec.env
```

**Comment by shivansh-gohem** [comment]
Hi @a-hilaly ,

I've been following the recent additions like Custom Types (#144) and External References (#72/#273). With those foundational pieces in place, this issue seems like the next logical step to enable dynamic resource generation.

I noticed you self-assigned this recently. Are you actively developing the core logic right now, or would you be open to me picking this up?

**Comment by a-hilaly** [comment]
@shivansh-gohem https://github.com/kubernetes-sigs/kro/pull/936

**Comment by shivansh-gohem** [comment]
@a-hilaly Understood, #936 looks massive! Great work.

I saw that Issue #957 (Conflict Detection) spawned from that PR. Since I just wrapped up the lifecycle safety work in #789, tackling conflict safety seems like the perfect follow-up for me.

Would you be open to me picking up #957?

**Comment by a-hilaly** [comment]
Feature just landed in 0.8.0:
- https://github.com/kubernetes-sigs/kro/releases/tag/v0.8.0
- https://kro.run/docs/concepts/rgd/resource-definitions/collections


/close

**Comment by gfaraj** [comment]
@a-hilaly this is great! Thanks.

Quick question, should I be able to do something like this?

```
status:
      queues: '${queues.map(q, {"name": q.spec.name, "queueName": q.status.queueName, "queueURL": q.status.queueURL, "queueArn": q.status.queueArn, "dlqURL": q.status.dlqURL, "dlqArn": q.status.dlqArn})}'

```
Where I have this:

```
- id: queues
      forEach:
        - queue: ${schema.spec.queues}
      template:
        apiVersion: sqs.infra.alkami.io/v1alpha1
        kind: Queue
        metadata:
          name: ${schema.metadata.name + '-' + queue.spec.name}'}
          namespace: ${schema.metadata.namespace}
          labels: ${schema.metadata.labels}
        spec: ${queue.spec}
```

I'm getting this error:

> 2026-01-30T23:37:42Z    ERROR    rgd-controller    Reconciler error    {"controller": "ResourceGraphDefinition", "controllerGroup": "kro.run", "controllerKind": "ResourceGraphDefinition", "name": "alkami-infra-stack", "reconcileID": "a4 │
│ 9133f3-0438-4a29-9b0b-4528d880a633", "error": "failed to build resourcegraphdefinition 'alkami-infra-stack': failed to build OpenAPI schema for instance status: failed to type-check status expression \"queues.map(q, {\\\"name\\\": q.spe │
│ c.name, \\\"queueName\\\": q.status.queueName, \\\"queueURL\\\": q.status.queueURL, \\\"queueArn\\\": q.status.queueArn, \\\"dlqURL\\\": q.status.dlqURL, \\\"dlqArn\\\": q.status.dlqArn})\" at path \"queues\": ERROR: <input>:1:1: expres │
│ sion of type '__type_queues' cannot be range of a comprehension (must be list, map, or dynamic)\n | queues.map(q, {\"name\": q.spec.name, \"queueName\": q.status.queueName, \"queueURL\": q.status.queueURL, \"queueArn\": q.status.queueAr │
│ n, \"dlqURL\": q.status.dlqURL, \"dlqArn\": q.status.dlqArn})\n | ^"}


I'm on kro 0.8.1.

I basically want to set a list or a map in the status field for all the resources in a collection.

**Comment by a-hilaly** [comment]
@gfaraj thank you for testing and reporting this quickly! I think that in theory what you're trying to do should work. However i'm not able to reproduce here, could you please share the full RGD (at least `spec.schema`) and the RGD used to create `sqs.infra.alkami.io/v1alpha1.Queue` ?

**Comment by a-hilaly** [comment]
Reproducing with ACK resources, I was able to get this get example processed and it's accepted by the controller:
```yaml
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: wrapped-queues
spec:
  schema:
    apiVersion: v1alpha1
    kind: WrappedQueue
    spec:
      queues: '[]string'
    status:
      queues: '${queues.map(q, {"name": q.metadata.name, "queueARN": q.status.ackResourceMetadata.arn})}'
  resources:
  - id: queues
    forEach:
    - queue: ${schema.spec.queues}
    template:
      apiVersion: sqs.services.k8s.aws/v1alpha1
      kind: Queue
      metadata:
        name: ${schema.metadata.name + '-' + queue}'
      spec: {}
```
I'm still a little suspicious that you might be dealing with a bug but i need more information/full example to be able to reproduce

**Comment by gfaraj** [comment]
@a-hilaly I tried your example and it errors out for me, so something might be wrong with my set up.

> "error": "failed to build resourcegraphdefinition 'wrapped-queues': failed to build OpenAPI schema for instance status: failed to type-check status expression \"queues.map(q, {\\\"name\\\": q.metadata.na │
│ me, \\\"queueARN\\\": q.status.ackResourceMetadata.arn})\" at path \"queues\": ERROR: <input>:1:1: expression of type '__type_queues' cannot be range of a comprehension (must be list, map, or dynamic)\n | queues.map(q, {\"name\": q.meta │
│ data.name, \"queueARN\": q.status.ackResourceMetadata.arn})\n | ^"}

I did notice that when I install my RGD through helm, I get a warning:

>I0130 17:37:42.228928   55316 warnings.go:110] "Warning: unknown field \"spec.resources[0].forEach\""

I can confirm that I have 0.8.1 in my cluster:

<img width="1105" height="618" alt="Image" src="https://github.com/user-attachments/assets/46edc223-53e7-4b6a-87d0-b3330a4f043c" />

**Comment by a-hilaly** [comment]
@gfaraj  Since helm doesn't upgrade CRDs by defaults, you might want to do that manually :) https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations 

I suspect kro didn't read any piece of data in the `forEach` directive because it was omitted by the API server, and that caused kro it to treat your resources as a non-collection one.

**Comment by gfaraj** [comment]
Ah, that was it, thanks @a-hilaly!  I applied [the crds](https://raw.githubusercontent.com/kubernetes-sigs/kro/refs/heads/main/helm/crds/kro.run_resourcegraphdefinitions.yaml) directly, and things are looking much better now.

I'm just running into a bit of an issue merging two objects. I'm assuming kro doesn't support merge yet. Is there another way to merge two objects?

```
  resources:
    - id: queues
      forEach:
        - queue: ${schema.spec.queues}
      template:
        apiVersion: sqs.infra.alkami.io/v1alpha1
        kind: Queue
        metadata:
          name: ${schema.metadata.name + '-' + queue.spec.name}'}
          namespace: ${schema.metadata.namespace}
          labels: ${schema.metadata.labels}
        spec: ${queue.spec.merge(schema.spec.setup)}
```

> "error": "failed to validate resource \"queues\": failed to type-check template expression \"queue.spec.merge(schema.spec.setup)\" at path \"spec\": ERROR: <input>:1:17: undeclared reference to 'merge' (in container '')\n | queue.spec.merge(schema.spec.setup)\n | ................^"}
