### ISSUE TITLE
detect and handle CRD breaking changes

### ISSUE THREAD

**Issue by a-hilaly** [kubernetes-sigs/kro#186]
### Feature Description

Currently kro does not detect breaking changes in `ResourceGroup` schemas when users modify them. Breaking changes like adding new required fields or removing existing fields can cause instance reconciliation failures. we need to add support for detecting such changes and marking the `ResourceGroup` as invalid. The system should also support an annotation 
(`kro.run/allow-breaking-changes: "true"`) to explicitly allow these changes when needed.

Examples:
```yaml
# Original ResourceGroup schema
apiVersion: kro.run/v1alpha1
kind: ResourceGroup
metadata:
  name: my-application
spec:
  schema:
    spec:
      name: string
      image: string | default="nginx"
```

```yaml
# Breaking change - adding a required field without default value
apiVersion: kro.run/v1alpha1
kind: ResourceGroup
metadata:
  name: my-application
  annotations:
    kro.run/allow-breaking-changes: "true"  # Required to apply breaking changes
spec:
  schema:
    spec:
      name: string
      image: string | default="nginx"
      port: number | require=true  # Breaking change: new required field
```
