### ISSUE TITLE
expose CEL expression execution cost in ResourceGroup status

### ISSUE THREAD

**Issue by a-hilaly** [kubernetes-sigs/kro#190]
### Feature Description

Currently there's no visibility into the cost of CEL expression evaluation for a ResourceGroup. We need to add support for tracking and exposing the total cost of CEL expressions in the ResourceGroup status. This will help platform teams understand the performance impact of their expressions and allow for better optimization of complex ResourceGroups.

Example:
```yaml
apiVersion: kro.run/v1alpha1
kind: ResourceGroup
metadata:
  name: my-application
spec: {...}
status:
  celMetrics:
    totalCost: 42      # Total cost across all expressions
    costPerResource:   # Breakdown per resource
      deployment: 12
      service: 8
      ingress: 22
```

[Like the Kubernetes API server does today, we want to add budgeting for CEL cost in kro. ](https://github.com/kubernetes/apiserver/blob/2241ea00526fdd746871375dfca871627f6a511a/pkg/apis/cel/config.go#L24-L26)
