### ISSUE TITLE
Kro is not supporting CEL raw string 

### ISSUE THREAD

**Issue by dirien** [kubernetes-sigs/kro#291]
### Description

**Observed Behavior**:

The Pulumi YAML support uses ${...} to evaluate expressions inside the `yaml`. When using this with we get following issue in our `rgd`: 

```bash
failed to validate resource CEL expressions: failed to dry-run expression project.id: failed to compile expression: ERROR: <input>:1:1: undeclared reference to 'project' (in container '')
```

Have a look into the `projectId` property. 

```yaml
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: my-pko-app
spec:
  schema:
    apiVersion: v1alpha1
    kind: MyApplication
    spec:
      name: string
      stack: string
      gitRepo: string
      region: string | default="nyc1"
      instanceCount: integer | default=1
      instanceSizeSlug: string | default="apps-s-1vcpu-1gb"
  resources:
  - id: program
    template:
      apiVersion: pulumi.com/v1
      kind: Program
      metadata:
        name: ${schema.spec.name}
      program:
        resources:
          project:
            type: digitalocean:Project
            properties:
              name: ${schema.spec.name}-project
              description: A project to represent development resources.
              purpose: Web Application
              environment: Development
          app:
            type: digitalocean:App
            properties:
              projectId: ${project.id}
              spec:
                name: app-${schema.spec.name}-${schema.spec.region}
                region: ${schema.spec.region}
                services:
                - name: app-service-${schema.spec.name}-${schema.spec.region}
                  instanceCount: ${schema.spec.instanceCount}
                  instanceSizeSlug: ${schema.spec.instanceSizeSlug}
                  git:
                    repoCloneUrl: ${schema.spec.gitRepo}
                    branch: "main"
  - id: stack
    template:
      apiVersion: pulumi.com/v1
      kind: Stack
      metadata:
        name: ${schema.spec.name}
      spec:
        stack: ${schema.spec.stack}
        envRefs:
          DIGITALOCEAN_TOKEN:
            type: Env
            env:
              name: DIGITALOCEAN_TOKEN
        programRef:
          name: ${schema.spec.name}
        destroyOnFinalize: true
```

More details about the Pulumi Property Access: https://www.pulumi.com/docs/iac/languages-sdks/yaml/yaml-language-reference/#property-access

To avoid this, I want to use the `raw` string support of CEL: https://github.com/google/cel-spec/blob/master/doc/langdef.md and "tell" kro to ignore the ${...} expression and leave it to the Pulumi Operator to do the work.

But this is not working.

**Expected Behavior**:

Use R or r to support raw strings in kro

**Reproduction Steps** (Please include `ResourceGraphDefinition` and `Instances` files):

```yaml
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: my-pko-app
spec:
  schema:
    apiVersion: v1alpha1
    kind: MyApplication
    spec:
      name: string
      stack: string
      gitRepo: string
      region: string | default="nyc1"
      instanceCount: integer | default=1
      instanceSizeSlug: string | default="apps-s-1vcpu-1gb"
  resources:
  - id: program
    template:
      apiVersion: pulumi.com/v1
      kind: Program
      metadata:
        name: ${schema.spec.name}
      program:
        resources:
          project:
            type: digitalocean:Project
            properties:
              name: ${schema.spec.name}-project
              description: A project to represent development resources.
              purpose: Web Application
              environment: Development
          app:
            type: digitalocean:App
            properties:
              projectId: R"${project.id}"
              spec:
                name: app-${schema.spec.name}-${schema.spec.region}
                region: ${schema.spec.region}
                services:
                - name: app-service-${schema.spec.name}-${schema.spec.region}
                  instanceCount: ${schema.spec.instanceCount}
                  instanceSizeSlug: ${schema.spec.instanceSizeSlug}
                  git:
                    repoCloneUrl: ${schema.spec.gitRepo}
                    branch: "main"
  - id: stack
    template:
      apiVersion: pulumi.com/v1
      kind: Stack
      metadata:
        name: ${schema.spec.name}
      spec:
        stack: ${schema.spec.stack}
        envRefs:
          DIGITALOCEAN_TOKEN:
            type: Env
            env:
              name: DIGITALOCEAN_TOKEN
        programRef:
          name: ${schema.spec.name}
        destroyOnFinalize: true
```

```yaml
apiVersion: kro.run/v1alpha1
kind: MyApplication
metadata:
  name: my-awsome-pko-based-app
spec:
  name: my-awesome-app
  stack: ediri/my-awesome-app/dev
  gitRepo: https://github.com/digitalocean/sample-vuejs
```

**Versions**:
- kro version: 0.2.1
- Kubernetes Version (`kubectl version`):  v1.31.1

**Involved Controllers**:
- Controller URLs and Versions (if applicable):

**Error Logs** (if applicable)**:
```
failed to validate resource CEL expressions: failed to dry-run expression project.id: failed to compile expression: ERROR: <input>:1:1: undeclared reference to 'project' (in container '')
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
