### ISSUE TITLE
Underlying resources don't get updated after changing Resource Graph Definitions Default

### ISSUE THREAD

**Issue by alicvsroxas** [kubernetes-sigs/kro#329]
### Description

When creating an underlying resource from a Resource Graph Definitions with default variables, and not specifying them in the underlying resource, whenever we change the defaults values in the Resource Graph Definitions the change isn't rolled out to the underlying resource.

**Observed Behavior**:
For simplicity, I created a Resource Graph Definition that deploys a Configmap with default variables:
```
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: test-configmap
spec:
  schema:
    apiVersion: v1alpha1
    kind: TestConfigmap
    spec:
      name: string
      namespace: string | default="default"
      # for example I change this default value:
      replicas: integer | default=4
      loglevel: string | default="info"
  resources:
    - id: configmap
      template:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: ${schema.spec.name}
          namespace: ${schema.spec.namespace}
        data:
          values.yaml: |
            replicas: ${schema.spec.replicas}
            logLevel: ${schema.spec.loglevel}

```
And called an underlying resource using the above RGD:
```
apiVersion: kro.run/v1alpha1
kind: TestConfigmap
metadata:
  name: test-configmap
spec:
  name: testtest
  namespace: default
```
Once the ConfigMap is created, I changed the default of replicas from 4 to 3.
Waited for a while, but the change I did in the RGD doesn't get replicated to the underlying resource created from it.
Observed this Behavior on other type of resources, deployments as well.

The logs I see Kro produce are:
```
2025-02-26T12:47:21.280Z    DEBUG    controller.resourceGraphDefinition    calculating resource graph definition status and conditions    {"resourcegraphdefinition": {"name":"test-configmap"}}
2025-02-26T12:47:21.280Z    DEBUG    controller.resourceGraphDefinition    updating resource graph definition status    {"resourcegraphdefinition": {"name":"test-configmap"}, "state": "Active", "conditions": 3}
2025-02-26T12:47:21.296Z    LEVEL(-5)    Reconcile successful    {"controller": "resourcegraphdefinition", "controllerGroup": "kro.run", "controllerKind": "ResourceGraphDefinition", "ResourceGraphDefinition": {"name":"test-configmap"}, "namespace": "", "name": "test-configmap", "reconcileID": "0e2e36d4-80d1-4a7e-8c84-52970a004b3d"}
2025-02-26T12:47:24.841Z    LEVEL(-2)    dynamic-controller    Skipping update due to unchanged generation    {"name": "test-configmap", "namespace": "default", "generation": 1} 
```

**Expected Behavior**:
The underlying resources created from a Resource Graph Definitions will be updated when I update the default variable in the schema, unless the underlying resource specified a value for the default.

**Versions**:
- kro version: 0.2.1
- Kubernetes Version (`kubectl version`): 1.31

### Which option describes the most your issue?

Instance (Create, Update, Deletion)

**Comment by gourav-k-shaw** [comment]
@alicvsroxas Can you please assign this issue to me.. i could work on this

**Comment by philipsabri** [comment]
I expected the [resync](https://github.com/kro-run/kro/blob/fa9b2f2e38b84dc4413483aa972459020fd17644/pkg/dynamiccontroller/dynamic_controller.go#L88) to handle this, but after testing the code it appears that [this section](https://github.com/kro-run/kro/blob/main/pkg/dynamiccontroller/dynamic_controller.go#L375-L381) completely bypasses it. It checks for a generation difference rather than any drift or new changes, as proven in your example.
https://github.com/kro-run/kro/blob/fa9b2f2e38b84dc4413483aa972459020fd17644/pkg/dynamiccontroller/dynamic_controller.go#L375-L380

I'm wondering if this behavior is intentional or a bug. https://github.com/kro-run/kro/blob/fa9b2f2e38b84dc4413483aa972459020fd17644/pkg/dynamiccontroller/dynamic_controller.go#L86-L88 It's possible I'm misinterpreting `will re-list` and it's not intended to update anything.

**Comment by tjololo** [comment]
Isn't this expected? Default is set in the CRD schema that is created based on the RGD.
This will in turn set the value in the custom resources (CR( when create without any explicit value set. [CRD default docs](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#defaulting)

Once this is done updating the RGD that in turn updates the CRD will not change defaults for existing CRs as I think the kro operator cannot determine if the value is set explicitly by the user or by the "default".
To have values that kro can change omit a default and use CEL to apply a default eg.
```
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: test-configmap
spec:
  schema:
    apiVersion: v1alpha1
    kind: TestConfigmap
    spec:
      name: string
      namespace: string | default="default"
      # for example I change this default value:
      replicas: integer
      loglevel: string | default="info"
  resources:
    - id: configmap
      template:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: ${schema.spec.name}
          namespace: ${schema.spec.namespace}
        data:
          values.yaml: |
            replicas: ${has(schema.spec.replicas) ? schema.spec.replicas : 4}
            logLevel: ${schema.spec.loglevel}
```

This will set the default at evaluation time instead of creation.

I haven't contributed to this project, but made the same discovery when testing kor. Investigating and checking with other operators I have written CRDs for lead me to this conclusion. 
My conclusion might be off, but decided to share my evaluation of the same issue
