### ISSUE TITLE
includeWhen not taken into account when evaluating CEL expressions

### ISSUE THREAD

**Issue by fsommar** [kubernetes-sigs/kro#417]
### Description

**Observed Behavior**:

Using indices in CEL expression fails when the index is > 1. It seems a bit inconsistent depending on the ordering of resources; sometimes index 1 works and sometimes it doesn't. Here's an example error message:

```
failed to validate resource CEL expressions:
  failed to dry-run expression schema.spec.berries[2]:
    failed to evaluate expression: index out of bounds: 2
```

It seems like it's not failing the type checking, but the evaluation and creation of the graph. I'm including a conditional `includeWhen` to exclude the resource, but it seems to not take that into account when validating the expressions.

**Expected Behavior**:

I expect the RGD below to successfully create and validate.

**Reproduction Steps** (Please include `ResourceGraphDefinition` and `Instances` files):

```yaml
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: berry-bush
spec:
  schema:
    apiVersion: v1alpha1
    kind: BerryBush
    spec:
      berries: '[]string | required'
  resources:
    - id: cm
      includeWhen:
        - ${schema.spec.berries.size() >= 3}
      template:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: '${schema.metadata.name}-${schema.spec.berries[2]}-cm'
```

**Versions**:
- kro version: 0.2.2
- Kubernetes Version (`kubectl version`): 1.27.1

---

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Which option describes the most your issue?

Common Expression Language (CEL), Directed Acyclic Graph inference
