### ISSUE TITLE
Unable to reconcile RGD if cluster contains unavailable APIService

### ISSUE THREAD

**Issue by maxsxu** [kubernetes-sigs/kro#457]
### Description

**Observed Behavior**:

The RGD inactive and has following error message

```
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
status:
  conditions:
  - lastTransitionTime: "2025-03-25T15:09:52Z"
    message: Directed Acyclic Graph is synced
    reason: failed to retrieve Kubernetes namespaced resources: unable to retrieve the complete list of server APIs: custom.api.server/v1alpha1: stale GroupVersion discovery: custom.api.server/v1alpha1....
    status: "False"
    type: GraphVerified
```

**Expected Behavior**:

The RGD should be reconciled successfully as long as the RGD resources doesn't refer any unavailable APIService.

**Reproduction Steps** (Please include `ResourceGraphDefinition` and `Instances` files):

Using example in https://kro.run/docs/getting-started/deploy-a-resource-graph-definition

**Versions**:
- kro version: 0.2.2
- Kubernetes Version (`kubectl version`): v1.32.3

**Involved Controllers**:
- Controller URLs and Versions (if applicable):

**Error Logs** (if applicable)**:
```
2025-03-25T15:09:52.492Z    DEBUG    controller.resourceGraphDefinition    processing reconciliation error    {"resourcegraphdefinition": {"name":"my-application"}, "error": "failed to retrieve Kubernetes namespaced resources: unable to retrieve the complete list of server APIs: custom.api.server/v1alpha1: stale GroupVersion discovery: custom.api.server/v1alpha1....."}
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Which option describes the most your issue?

ResourceGraphDefinition (Create, Update, Deletion)
