### ISSUE TITLE
Cluser scoped resources and owner references

### ISSUE THREAD

**Issue by nabuskey** [kubernetes-sigs/kro#48]
Related to #44 

If you create a RG with cluster resources, the owner references cannot point to the correct instance of RG.

RG:

```yaml
apiVersion: x.symphony.k8s.aws/v1alpha1
kind: ResourceGroup
metadata:
  name: deploymentservice.x.symphony.k8s.aws
  namespace: ns1
spec:
  apiVersion: v1alpha1
  kind: DeploymentServiceTest
  definition:
    spec:
      name: string
      namespace: string | default=default
  resources:
  - name: clusterrole
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: pod-reader
      rules:
        - apiGroups: [ "" ]
          resources: [ "pods" ]
          verbs: [ "get", "watch", "list" ]
```

instance
```yaml
apiVersion: x.symphony.k8s.aws/v1alpha1
kind: DeploymentServiceTest
metadata:
  name: my-deployment-and-service3
  namespace: ns1
spec:
  name: app3
  namespace: ns1
```
ClusterRole created:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
  ownerReferences:
  - apiVersion: x.symphony.k8s.aws/v1alpha1
    controller: true
    kind: DeploymentServiceTest
    name: my-deployment-and-service3
    uid: ab1b4ed8-fd0a-4d39-812e-3f9de8c7239f
```

This is incorrect because the DeploymentServiceTest object is in the ns1 namespace. 

The namespace field does not exist on the struct because k8s does not allow namespaced objects owning cluster objects.
https://github.com/kubernetes/apimachinery/blob/c463db196543ee48d2353c6ca3325de6454ad075/pkg/apis/meta/v1/types.go#L291-L320

The ownership relationship is lost and tools like argocd / lineage cannot make sense of these resources.
