### ISSUE TITLE
Drift Detection Not Working for Deployment Replicas Changes in v0.2.3

### ISSUE THREAD

**Issue by blackdog0403** [kubernetes-sigs/kro#516]
### Description
The drift detection mechanism is not functioning as expected when deployment replicas are manually changed. Even with `config.dynamicControllerDefaultResyncPeriod=30` set, the controller does not detect or log changes when deployment replicas are modified outside of KRO.

### Version
- KRO Version: 0.2.3

### Configuration
```yaml
config.dynamicControllerDefaultResyncPeriod=30
```

### Resource Graph Definition
```yaml
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  # need better name for example
  name: web-application-rgd
spec:
  # kro uses this simple schema to create your CRD schema and apply it
  # The schema defines what users can provide when they instantiate the RGD (create an instance).
  schema:
    apiVersion: v1alpha1
    kind: WebApplication
    spec:
      # Spec fields that users can provide.
      name: string
      image: string | default="nginx"
      ingress:
        enabled: boolean | default=false
      replicas: integer | default=1
    status:
      # Fields the controller will inject into instances status.
      deploymentConditions: ${deployment.status.conditions}
      availableReplicas: ${deployment.status.availableReplicas}

  # Define the resources this API will manage.
  resources:
    - id: deployment
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: ${schema.spec.name} # Use the name provided by user
        spec:
          replicas: ${schema.spec.replicas}
          selector:
            matchLabels:
              app: ${schema.spec.name}
          template:
            metadata:
              labels:
                app: ${schema.spec.name}
            spec:
              containers:
                - name: ${schema.spec.name}
                  image: ${schema.spec.image} # Use the image provided by user
                  ports:
                    - containerPort: 80

    - id: service
      template:
        apiVersion: v1
        kind: Service
        metadata:
          name: ${schema.spec.name}-service
        spec:
          selector: ${deployment.spec.selector.matchLabels} # Use the deployment selector
          ports:
            - protocol: TCP
              port: 80
              targetPort: 80

    - id: ingress
      includeWhen:
        - ${schema.spec.ingress.enabled} # Only include if the user wants to create an Ingress
      template:
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: ${schema.spec.name}-ingress
          annotations:
            kubernetes.io/ingress.class: alb
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: ip
            alb.ingress.kubernetes.io/healthcheck-path: /health
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
            alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=60
        spec:
          rules:
            - http:
                paths:
                  - path: "/"
                    pathType: Prefix
                    backend:
                      service:
                        name: ${service.metadata.name} # Use the service name
                        port:
                          number: 80

```

### Instance
```
apiVersion: kro.run/v1alpha1
kind: WebApplication
metadata:
  name: web-app-first
spec:
  name: first-kro-app
  ingress:
    enabled: true
  replicas: 3
```

### Steps to Reproduce
1. Apply the above ResourceGraphDefinition
2. Manually change the replicas in the deployment using kubectl
3. Wait for more than 30 seconds
4. Check KRO controller logs

### Expected Behavior
- The controller should detect the drift in replica count
- Controller logs should show delta changes
- The replica count should be reconciled back to the original value

### Actual Behavior
- No drift detection occurs
- No delta changes are logged in the controller
- The manually changed replica count remains unchanged
- If I delete KRO pod and restart, then I catches drift between desire state(spec) and actual state then reconcile.

### Additional Context
The drift detection functionality appears to be non-functional despite the configuration being set correctly according to documentation.
```
