### ISSUE TITLE
RGD creation fails when we have map access

### ISSUE THREAD

**Issue by barney-s** [kubernetes-sigs/kro#535]
### Description

**Observed Behavior**:
Installing RGD , 
RGD status:
```
 status:
    conditions:
    - lastTransitionTime: "2025-05-05T17:46:12Z"
      message: Directed Acyclic Graph is synced
      reason: 'failed to validate resource CEL expressions: failed to ensure resource
        deployment expressions: failed to dry-run expression configmap.data["env"]:
        failed to dry-run expression configmap.data["env"]: failed to evaluate expression:
        no such key: env'
      status: "False"
      type: GraphVerified
```
**Expected Behavior**:
RGD should install.

**Reproduction Steps** (Please include `ResourceGraphDefinition` and `Instances` files):
https://github.com/kro-run/kro/compare/main...barney-s:kro:map-access

```
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: envdeployment.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: EnvDeployment
    spec:
      env: string | default="value"
    status:
      deploymentConditions: ${deployment.status.conditions}
      availableReplicas: ${deployment.status.availableReplicas * 10}
  resources:
    - id: configmap
      template:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: ${schema.metadata.name}
        data:
          env: ${schema.spec.value}
    - id: deployment
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: ${schema.metadata.name}
          labels:
            env: ${configmap.data["env"]}
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: deployment
          template:
            metadata:
              labels:
                app: deployment
            spec:
              containers:
                - name: ${schema.metadata.name}-deployment
                  image: nginx
                  ports:
                    - containerPort: 80
```

**Versions**:
- kro version: 0.2.4
- Kubernetes Version (`kubectl version`): 1.32.2

**Error Logs** (if applicable)**:
```
Paste any relevant logs here
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
