### ISSUE TITLE
Dynamic default values in schema

### ISSUE THREAD

**Issue by joshuabaird** [kubernetes-sigs/kro#579]
### Feature Description

**Problem Statement**:
I would like to provide a dynamic value as a default value in my RGD spec:

```
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: applicationiam.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: ApplicationIAM
    spec:
      name: string | default=${schema.spec.namespace}
```

**Alternatives Considered**:
You could use `${schema.spec.namespace}` directly in the resource template, but this would mean the user is unable to override it if needed.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue
* If you are interested in working on this feature, please leave a comment
